# Generated by Django 6.0 on 2026-01-06 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_passwordresetotp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PasswordResetOTP',
        ),
    ]
