# Generated by Django 6.0 on 2026-01-10 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0008_userprofile_delete_reportissue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
        migrations.DeleteModel(
            name='PasswordResetOTP',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
