# Generated by Django 6.0.1 on 2026-01-12 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0010_alter_user_username_passwordresetotp_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyerreport',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified/Resolved')], default='pending', max_length=20),
        ),
    ]
