# Generated by Django 6.0 on 2026-01-12 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0011_buyerreport_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
