# Generated by Django 6.0 on 2026-01-13 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0013_listing_admin_note_listing_area_listing_bathrooms_and_more'),
        ('task', 'merge_0012_conflict'),
    ]

    operations = [
    ]
