# Generated by Django 6.0 on 2026-01-13 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0014_merge_20260113_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='area',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='bathrooms',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='bedrooms',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='monthly_rent',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
