# Generated by Django 6.0 on 2026-01-13 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0015_alter_listing_area_alter_listing_bathrooms_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OldListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('status', models.CharField(default='Pending', max_length=20)),
            ],
        ),
    ]
