# Generated by Django 6.0 on 2026-01-13 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0017_create_listingphoto_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listingphoto',
            old_name='created_at',
            new_name='uploaded_at',
        ),
        migrations.AddField(
            model_name='listingphoto',
            name='is_proof',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='listingphoto',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='task.listing'),
        ),
    ]
