# Generated by Django 6.0 on 2026-01-17 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_buyerreport_resolved_at_notification'),
        ('task', '0019_merge_20260116_2032'),
    ]

    operations = [
    ]
