# Generated by Django 6.0 on 2026-01-17 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0020_merge_20260117_1907'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
