# Generated by Django 6.0 on 2026-02-01 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0023_listing_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
