# Generated by Django 6.0 on 2026-02-20 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0024_listing_latitude_listing_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='ac_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='has_balcony',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='kitchen_type',
            field=models.CharField(blank=True, choices=[('attached', 'Attached Kitchen'), ('shared', 'Shared Kitchen'), ('none', 'No Kitchen')], max_length=20),
        ),
        migrations.AddField(
            model_name='listing',
            name='lift_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='pet_allowed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='total_area',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='water_24hrs',
            field=models.BooleanField(default=False),
        ),
    ]
