# Generated by Django 6.0 on 2026-02-21 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0030_alter_listing_latitude_alter_listing_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=9, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=9, max_digits=18, null=True),
        ),
    ]
