# Generated by Django 6.0 on 2026-02-23 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0033_alter_message_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
