# Generated by Django 6.0 on 2026-02-23 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0034_listing_deleted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='listing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='task.listing'),
        ),
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('listing_unavailable', 'Listing Unavailable'), ('listing_available', 'Listing Available'), ('listing_deleted', 'Listing Deleted'), ('message', 'New Message'), ('general', 'General')], default='general', max_length=50),
        ),
        migrations.AddField(
            model_name='notification',
            name='title',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
